"""
Churn-prediction API: GET /health, POST /predict, POST /chat, and
DELETE /chat/{session_id}. The XGBoost model (the full preprocessing +
classifier pipeline, from its MLflow run artifact) is loaded once at
startup, not per-request. The LangChain agent (src/agent/agent.py) is
imported once at module load for the same reason.
"""

import logging
from contextlib import asynccontextmanager

import mlflow
import mlflow.sklearn
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

from src.agent.agent import agent as churn_agent
from src.agent.semantic_cache import check_semantic_cache, store_in_semantic_cache
from src.models.train_baseline import EXPERIMENT_NAME, MLFLOW_TRACKING_URI, prepare_model_input
from src.serving.feature_cache import get_customer_features

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger("api")

model_state = {}


def load_latest_xgboost_pipeline():
    mlflow.set_tracking_uri(MLFLOW_TRACKING_URI)
    client = mlflow.tracking.MlflowClient()
    experiment = client.get_experiment_by_name(EXPERIMENT_NAME)
    if experiment is None:
        raise RuntimeError(f"MLflow experiment '{EXPERIMENT_NAME}' not found")

    runs = client.search_runs(
        [experiment.experiment_id],
        filter_string="tags.mlflow.runName = 'xgboost'",
        order_by=["start_time DESC"],
        max_results=1,
    )
    if not runs:
        raise RuntimeError(f"No 'xgboost' run found in MLflow experiment '{EXPERIMENT_NAME}'")

    run_id = runs[0].info.run_id
    pipeline = mlflow.sklearn.load_model(f"runs:/{run_id}/model")
    logger.info("Loaded xgboost model from run %s", run_id)
    return pipeline, run_id


@asynccontextmanager
async def lifespan(app: FastAPI):
    model_state["pipeline"], model_state["run_id"] = load_latest_xgboost_pipeline()
    yield
    model_state.clear()


app = FastAPI(lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://localhost:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Session_id -> full LangChain message list for that conversation. In-memory
# only: this is deliberately simple for now - it won't survive a server
# restart (--reload will wipe it on every code change too) and isn't safe
# across multiple server instances/workers, since each process has its own
# dict. A real deployment would back this with Redis or a proper session
# store instead.
chat_sessions: dict[str, list] = {}


class PredictRequest(BaseModel):
    customer_id: str


class ChatRequest(BaseModel):
    session_id: str
    message: str


@app.get("/health")
def health():
    return {"status": "ok"}


@app.post("/predict")
def predict(req: PredictRequest):
    features, cache_hit = get_customer_features(req.customer_id)
    if features is None:
        raise HTTPException(status_code=404, detail=f"customer_id '{req.customer_id}' not found")

    X = prepare_model_input(features)
    churn_probability = float(model_state["pipeline"].predict_proba(X)[0, 1])
    prediction = "Yes" if churn_probability >= 0.5 else "No"

    return {
        "customer_id": req.customer_id,
        "churn_probability": round(churn_probability, 4),
        "prediction": prediction,
        "cache_hit": cache_hit,
    }


@app.post("/chat")
def chat(req: ChatRequest):
    previous_messages = chat_sessions.get(req.session_id, [])
    is_first_message = not previous_messages

    # Semantic cache only applies to the first message of a session - the
    # same question mid-conversation can mean something different given
    # prior context, so it's only safe to short-circuit on a fresh session.
    if is_first_message:
        cached = check_semantic_cache(req.message)
        if cached is not None:
            chat_sessions[req.session_id] = [
                {"role": "user", "content": req.message},
                {"role": "assistant", "content": cached["response"]},
            ]
            return {
                "session_id": req.session_id,
                "response": cached["response"],
                "tool_calls": cached["tool_calls"],
            }

    input_messages = previous_messages + [{"role": "user", "content": req.message}]

    result = churn_agent.invoke({"messages": input_messages})
    chat_sessions[req.session_id] = result["messages"]

    # only the messages generated by this turn (not prior turns already
    # reported to the caller before), so tool_calls reflects just this call
    new_messages = result["messages"][len(input_messages):]

    tool_calls = [
        {"tool": call["name"], "args": call["args"]}
        for msg in new_messages
        for call in (getattr(msg, "tool_calls", None) or [])
    ]

    response_text = new_messages[-1].content if new_messages else ""

    if is_first_message:
        store_in_semantic_cache(req.message, response_text, tool_calls)

    return {
        "session_id": req.session_id,
        "response": response_text,
        "tool_calls": tool_calls,
    }


@app.delete("/chat/{session_id}")
def clear_chat(session_id: str):
    existed = chat_sessions.pop(session_id, None) is not None
    return {"session_id": session_id, "cleared": existed}
